### ISSUE TITLE
Odd quoting in output

### ISSUE THREAD

**Issue by jorgenpt** [proletariatgames/p4harmonize#11]
It looks like all the double quotes in `p4harmonize`'s output are escaped in the log output, which is a little confusing. For example:

```
2023.12.15-20:13:45   --> Exec: p4 -p ssl:perforce.example.com:1666 -u jorgen -c ec2_ondemand_engine_sync_harmonize -x \"/tmp/p4harmonize_delete_3938411009.txt\" delete -c 45400
2023.12.15-20:13:45   --> Exec: p4 -p ssl:perforce.example.com:1666 -u jorgen -c ec2_ondemand_engine_sync_harmonize add -c 45400 -t text -I -f \"/home/ubuntu/ws/org-harmonize/Engine/Source/ThirdParty/CEF3/Build/linux/Toolchain-clang.cmake\"
2023.12.15-20:13:45   --> //proj/engine/Engine/Source/ThirdParty/CEF3/Build/linux/Toolchain-clang.cmake#3 - opened for add
2023.12.15-20:13:45   --> Exec: p4 -p ssl:perforce.example.com:1666 -u jorgen -c ec2_ondemand_engine_sync_harmonize revert -a -c 45400 \"/home/ubuntu/ws/org-harmonize/...\"
2023.12.15-20:13:45 Success! All changes are waiting in CL #45400. Please review and submit when ready.
2023.12.15-20:13:45 Remember to delete workspace \"ec2_ondemand_engine_sync_harmonize\"
2023.12.15-20:13:45 and local folder \"/home/ubuntu/ws/org-harmonize\"
```

Both the arguments to `p4 delete` are escaped in the terminal and the workspace name & local folder in the final status message, along with other messages. I wouldn't expect backslashes here -- it makes it hard to copy-paste the output to e.g. run a command manually or copy the path name.

**Comment by danbrakeley** [comment]
Yeah, I agree with you. The escapes are happening in the logger, frog, but I don't think that the logger should escape those quotes in that case. I'll push a new version of frog, then update p4harmonize to use it.

**Comment by danbrakeley** [comment]
OK, should be fixed in the latest release: https://github.com/danbrakeley/p4harmonize/releases/tag/v0.6.0
