### ISSUE TITLE
Source and destination servers with different unicode mode

### ISSUE THREAD

**Issue by kalihman** [proletariatgames/p4harmonize#12]
Hello! Thank you for open-sourcing this great codebase. I'm using this software to copy a licensee stream from Epic to my Perforce server. It turns out, Epic's server is in non-unicode mode and my server is in unicode mode(utf8). When I run this software, I get this error.

```
2024.07.02-17:59:36 Config loaded from C:\\Users\\user\\p4harmonize_config.toml
2024.07.02-17:59:36   >>- Exec: p4 -p ssl:p4-licensee.epicgames.com:1666 -u USER login -s
2024.07.02-17:59:37   >>- Error checking login status on ssl:p4-licensee.epicgames.com:1666: Unicode clients require a unicode enabled server.\r
2024.07.02-17:59:37 pre-flight checks failed
2024.07.02-17:59:37 Running Time: 333.2546ms
```

Client P4CHARSET env variable is utf8 and I cannot connect to non-unicode server from this environment. Is there any part of the code that I can change to alleviate this issue?

**Comment by danbrakeley** [comment]
Hey, apologies for the slow response. This is an area of perforce I haven't done a deep dive on yet, but I bet there's something we could be passing to p4 commands that tell it to operate in whatever the charset is that the epic server is using.

The best way to start debugging this issue will be to get p4harmonize's longtest to fail with that same error. Running longtest requires Docker to be available locally (see the README.md for details), but once it has a failing test for this, it should be easy to try things out and find the right combination of command line args that addresses this.

I can spend maybe an hour on this now, and then I'll see if I have more time later in the week to come back to it.

**Comment by danbrakeley** [comment]
@kalihman ok! I've got a new release that I think should address this problem: https://github.com/danbrakeley/p4harmonize/releases/tag/v0.7.0

If that doesn't fix it for you, feel free to open a new issue.

**Comment by kalihman** [comment]
This is the exact thing I've looking for. Thanks for the quick patch!
